language: objective-c
before_install:
  - gem install cocoapods
  - brew update
  - brew upgrade xctool
before_script:
  - export LANG=en_US.UTF-8
  - cd Example/iOS ; pod install ; cd ../..
script: xctool -workspace Example/iOS/RPJSContextDemo.xcworkspace -scheme RPJSContextDemo -sdk iphonesimulator test