pod "RPJSContext", :path => "../../"

target "RPJSContextDemoTests" do
    pod 'Specta', :git => 'git@github.com:specta/specta.git', :branch => '0.3-wip'
    pod 'Expecta', '~> 0.3.0'
end

post_install do |installer|
    target = installer.project.targets.find { |t| t.to_s == "Pods-RPJSContextDemoTests-Specta" }
    if (target)
        target.build_configurations.each do |config|
            s = config.build_settings['FRAMEWORK_SEARCH_PATHS']
            s = [ '$(inherited)' ] if s == nil;
            s.push('$(PLATFORM_DIR)/Developer/Library/Frameworks')
            config.build_settings['FRAMEWORK_SEARCH_PATHS'] = s
        end
        else
        puts "WARNING: Pods-RPJSContextDemoTests-Specta target not found"
    end
end